### PR TITLE
Prevent NPE in FlightRecorderFilter if event recording is not active

### PR DESCRIPTION
**Pull request by thomasdarimont**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Good catch; thanks a lot, @thomasdarimont!

**Comment by gunnarmorling** [comment]
The event initially was held in a ThreadLocal (inspired by existing JDK event types), so this could never happen. Then I changed it into the current form for sake of simplicity, and there you have it :) Thanks again!

**Comment by thomasdarimont** [comment]
I was already wondering whether ThreadLocal storage would make more sense to reduce heap pressure :)

**Comment by gunnarmorling** [comment]
So the (most?) built-in event types do that; in that particular case I
don't think it'd make a difference, as it's a single object allocation
for a REST call which surely creates many other objects, too. Would be
different in a tight loop.

**Comment by thomasdarimont** [comment]
I think you're right, it doesn't matter much in this case.

**Pull request merged**
